#! /bin/sh

bspc config border_width               5
bspc config window_gap                 5
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config pointer_follows_monitor    true
bspc config click_to_focus             button1

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8

bspc config top_padding                25
bspc config bottom_padding             0
bspc config right_padding              0
bspc config left_padding               0

bspc config normal_border_color        '#555555'
bspc config focused_border_color       '#005FAF'

bspc rule -a mpv state=floating
bspc rule -a sxiv state=floating
bspc rule -a thunar state=floating
bspc rule -a Wine state=floating
bspc rule -a MPlayer state=floating
bspc rule -a gmplayer state=floating
bspc rule -a qemu-system-i386 state=floating
bspc rule -a qemu-system-x86_64 state=floating

#wmname LG3D
wmsetbg -S -f $HOME/images/f31721216.jpg
xsetroot -cursor_name left_ptr
#$HOME/usr/bin/panel-info 2> /dev/null &
compton -b --config $HOME/.config/compton/compton.conf
polybar -r example &
blueman-applet &
nm-applet &
artha &
copyq &
zeal &
megasync &
qbittorrent &
